from todomvc_testing.Model import todos

def test_e2e():
    todos.given_opened('Task 1', 'Task 2')
    todos.should_be('Task 1', 'Task 2')
    todos.should_size(2)
    todos.edit_double_click('Task 1', 'New Task 1')
    todos.should_be('New Task 1', 'Task 2')
    todos.toggle_click('New Task 1')
    todos.completed_click()
    todos.should_be('New Task 1')
    todos.all_click()
    todos.toggle_click('Task 2')
    todos.completed_click()
    todos.should_size(2)
    todos.should_be('New Task 1', 'Task 2')
    todos.all_click()
    todos.clear_completed()
    todos.should_size(0)
    todos.add('New Task 1', 'Task 2')
    todos.hover_destroy('Task 2')
    todos.should_be('New Task 1')
    todos.should_size(1)
    todos.hover_destroy('New Task 1')
    todos.should_size(0)
